### ISSUE TITLE
This repository is missing a license

### ISSUE THREAD

**Issue by maxhbr** [nix-community/nixos-generators#10]
This project needs a license to be open source. See e.g. https://choosealicense.com/. Other projects within `nix-community` seem to be licensed under MIT.

**Comment by Lassulus** [comment]
where do i do that?

**Comment by maxhbr** [comment]
If you would choose MIT (what I recommend), you could simply copy the file https://github.com/nix-community/NUR/blob/master/LICENSE, adopt it to your copyright, and place it in the project root. It would also be good if you mention in the footer of the readme that this project is licensed under MIT.

**Comment by Lassulus** [comment]
thanks, should be fixed by https://github.com/nix-community/nixos-generators/commit/bbe9e78bb308434f133d048aac54fb676afb0f20 now
