### ISSUE TITLE
How to use `--flake`

### ISSUE THREAD

**Issue by Mic92** [nix-community/nixos-generators#110]
it seems that `nixosConfigurations.<machine>`  is not overridable, hence the question is how to use `--flake`.

**Comment by Sorixelle** [comment]
Looks like it depends on NixOS/nixpkgs#101475. A workaround for now would be doing something like:
```nix
{
  nixosConfigurations = let
    lib = nixpkgs.lib;
  in {
    machineName = (lib.makeOverridable lib.nixosSystem) {
      # ...
    };
  };
}
```

**Comment by legendofmiracles** [comment]
How do you even get so far? Whenever I try to use the --flake option it tells me that the option is not found:
```
> nixos-generate --system aarch-64 --flake dotnix#nixosConfigurations.pi
error: 'flake' is not a recognised command
Try 'nix --help' for more information.
```
Weirdly enough the error itself seems to be coming from nix. Not nixos-generate...

**Comment by Sorixelle** [comment]
You need to make sure `nixos-generate` is using a flake-enabled Nix (ie. `nixos-generate.override { nix = nixUnstable; }`).

**Comment by Pacman99** [comment]
Can the `--flake` feature be implemented with https://github.com/NixOS/nixpkgs/pull/143207 instead? It seems like that could be a better solution and not require users to set `mkOverridable`
