### ISSUE TITLE
cd-dvd/sd-image.nix is deprecated

### ISSUE THREAD

**Issue by oldaccountdeadname** [nix-community/nixos-generators#112]
I'm compiling some images for an rPi, and came across a warning that `installer/cd-dvd/sd-image.nix` is deprecated. I *believe* all that needs to be done is to swap out cd-dvd with sd-card in formats/sd-aarch64.nix and formats/sd-aarch64-installer.nix`, pseudo-patch below:

```patch
  imports = [
-  "${toString modulesPath}/installer/cd-dvd/sd-image.nix
+  "${toString modulesPath}/installer/sd-card/sd-image.nix
  ];
```

I'm not at all familiar with this project and only slightly experienced with Nix, so I'm not sure if the above would break things. As it stands, though, it *does* look like installer/cd-dvd/sd-image.nix is deprecated and needs to be moved away from. Thanks!

**Comment by LincolnAuster** [comment]
Thanks so much!
