### ISSUE TITLE
QEMU errors with 'Duplicate ID 'user.0' for netdev'

### ISSUE THREAD

**Issue by max-niederman** [nix-community/nixos-generators#113]
When running `nixos-generate -f vm --run` or `nixos-generate -f vm-bootloader --run` I get the following error:
```
qemu-system-x86_64: -netdev user,id=user.0,hostfwd=tcp::8088-:80,hostfwd=tcp::8022-:22: Duplicate ID 'user.0' for netdev
```

After some trial and error, I was able to get it working by creating a custom format identical to `formats/vm.nix`, but without the `virtualisation.qemu.networkingOptions` key. I believe this is because the options specified in the format collide with those passed to QEMU in the generated `run-nixos-vm` script which `nixos-generate` uses to run the VM.

**Comment by max-niederman** [comment]
Upon further inspection, this did not actually solve the issue, just remove the network device entirely, which prevents the VM from booting.

**Comment by Lassulus** [comment]
alright, could reproduce it on unstable, I guess this was introduced by https://github.com/NixOS/nixpkgs/pull/127933 but there is now actually an option for forwarding ports. So I would go with disable them by default and people can just forward ports in their respective configurations.

**Comment by Lassulus** [comment]
alright, I removed the value in https://github.com/nix-community/nixos-generators/commit/3ede4cca3d82bf61e164100c79917cb8c50e2087 so this should be fixed now?

If you want to still use the port forwarding, which is now removed, you can define it like this in your configuration:
```
virtualisation.forwardPorts = [
  { from = "host"; host.port = 2222; guest.port = 22; }
];
```
