### ISSUE TITLE
How to use custom formats when using generators as a flake?

### ISSUE THREAD

**Issue by sagikazarmark** [nix-community/nixos-generators#133]
I'd like to experiment with building vmware vagrant boxes (similar to the vagrant-virtualbox format). How can I add custom formats when I use nixos-generators in a flake?

**Comment by Mic92** [comment]
For now you need to point to your own fork of nixes-generators that has them.
Available formats are hard-coded: https://github.com/nix-community/nixos-generators/blob/296067b9c7a172d294831dec89d86847f30a7cfc/flake.nix#L15

**Comment by Lassulus** [comment]
there is also `--format-path`

**Comment by sagikazarmark** [comment]
Thanks folks! I forked the repo for now.
