### ISSUE TITLE
no /etc/nixos/configuration.nix for qcow/raw format

### ISSUE THREAD

**Issue by cherusk** [nix-community/nixos-generators#134]
Would be nice to have the actual configuration.nix put in place.

Copying over in hindsight and rebuilding comes with problems, e.g. for file systems.

**Comment by cherusk** [comment]
That's the error one can get when rebuilding with originally used configuration.nix

> error:
> Failed assertions:
> - The ‘fileSystems’ option does not specify your root file system.
> - You must set the option ‘boot.loader.grub.devices’ or 'boot.loader.grub.mirroredBoots' to make the system bootable.

**Comment by Lassulus** [comment]
hmm, well my hands are tied in that regard. there is no real good way to copy you configuration files (since they could be split over multiple files/directories/repos). so this is something that needs to be done by the person specifying the config/building the image. maybe we can insert the fileSystems in some way. but no idea comes to my mind. Can you test setting `system.copySystemConfiguration = true` in you config and building it again?

**Comment by cherusk** [comment]
@Lassulus

Your point about modular configuration is quite profound.

My problem is less about getting the configuration placed, than trackability of what settings are applied.

Maybe let me describe better the situation I was struggling with. That might leads to another issue.

So I'm building nixos vm images in a workflow and I spin those up at some point in a test stack. Nothing exciting.

But for example when I apply this setting:

> https://github.com/cherusk/godon/pull/46/files#diff-> 5d5447499c89d6e551e7911c5457f02be5e5477a1ef8a1806071673fa308e728R29

The image builds, but the firewall is not off when I spin up the resulting image.

Though, when I copy over the same configuration.nix that I used to build the vm image into the running instance and rebuild and load it, then the firewall setting takes effect. Would have been nice to know why and a lacking reference configuration in the running image of what has been applied makes it harder.

So then maybe time for a separate issue of that firewall setting not working with nixos-generators.

**Comment by Mic92** [comment]
How do you run `nixos-generators`?

**Comment by cherusk** [comment]
@Mic92 
Here https://github.com/cherusk/godon/blob/d7859c2e05100e471f93109fee3724e74ba4314c/.github/workflows/test_stack.yml#L52, it's part of a workflow when I want to recreate the teststack.

**Comment by cherusk** [comment]
So I'm fine with closing this.

I've a workaround, loading over the configuration and rebuilding it once instance has been created as mentioned previously.

**Comment by Lassulus** [comment]
would be still interesting to debug that firewall issue
