### ISSUE TITLE
Note jq dependency or add nix-shell shebang

### ISSUE THREAD

**Issue by ryantm** [nix-community/nixos-generators#14]
The script depends on jq

```
$ ./nixos-generate  -f install-iso                                                                                       |                                                                                                                                                              
./nixos-generate: line 104: jq: command not found  
```

I got around this by doing

```
nix-shell -p jq
```
It would be nice to note this dependency in the readme, or use a nix-shell shebang to automatically make jq available tot he script.

**Comment by Lassulus** [comment]
should be fixed by: https://github.com/nix-community/nixos-generators/commit/ca7df9db1e358b5b3eaf4c3c88d9c124a7dece04
