### ISSUE TITLE
On WSL2 stopped working

### ISSUE THREAD

**Issue by 573** [nix-community/nixos-generators#158]
Using `nix --extra-experimental-features "nix-command flakes" run github:nix-community/nixos-generators -- --help` on a WSL2 NixOS instance I get

>error: attribute 'defaultApp.x86_64-linux' should have type 'derivation'

lately.

Pretty sure it worked before.

Is i. e. `nix --extra-experimental-features "nix-command flakes" run github:nix-community/nixos-generators --inputs-from github:nix-community/nixos-generators/85014f3 -- --help`

the right approach to use a different commit of nixos-generators to check for potential regression ?

# More context

```console
nix-shell --command './nixos-generate --help
```

on the a fresh clone of the repo just works. Seems to be flakes-related only.

**Comment by Mic92** [comment]
I have seen this on other projects as well. It seems that nix now wants always a `defaultApp` in a flake or it fails.

**Comment by 573** [comment]
@Mic92 thanks, then I'd resort to `nix --extra-experimental-features "nix-command flakes" shell github:nix-community/nixos-generators -c nixos-generate --help`.
