### ISSUE TITLE
[Feature Request] Add support for linode custom images

### ISSUE THREAD

**Issue by arouzing** [nix-community/nixos-generators#169]
Linode now has support for prebuilt images.
Support for it would be well suited on this project.

Here is the relevant information regarding how the images must be built.

Useful nixos specific install information:
https://www.linode.com/docs/guides/install-nixos-on-linode/
Linode image specifications:
https://www.linode.com/docs/products/tools/images/
https://www.linode.com/docs/products/tools/images/guides/upload-an-image/#requirements-and-considerations

Overview of specifications

- compressed raw image in gzip format .img.gz
- uncompressed result should be no greater then 6gb
- file format ext(3/4)
-  needs custom boot delay of 10 seconds
- custom tty
Wanted to say love the project. It is a huge timesaver for my other deployments so far!

**Comment by pgronkievitz** [comment]
wasn't this closed by #175?

**Comment by arouzing** [comment]
> wasn't this closed by #175?

Looks to be correct! With that, I'll close my issue. Thanks!
