### ISSUE TITLE
Is there a particular reason why nixos-generators follows unstable?

### ISSUE THREAD

**Issue by mainrs** [nix-community/nixos-generators#178]
I usually pin my system to the latest release. Does making nixos-generators follow the pinned version break things? As far as I can tell this project fetches packages from the nixpkgs that I pass to it/specify using follows.

**Comment by Lassulus** [comment]
It could break things, I usually follow unstable on my development machines. I would recommend using the in nixpkgs packaged version if you follow stable

**Comment by mainrs** [comment]
So if I follow release-21.11 I should pass down that nixpkgs version to nixos-generators?

**Comment by Lassulus** [comment]
not sure why you would need to pass that if it's your default nixpkgs? What I meant is to use `nix-shell -p nixos-generators` (or something like that) and it will use the nixos-generators version matching to your nixpkgs version
