### ISSUE TITLE
Cross compiling from aarch64-darwin?

### ISSUE THREAD

**Issue by supermarin** [nix-community/nixos-generators#187]
For some reason I lived under impression that I was cross compiling a qcow aarch64-linux vm from a M1 mac. Turns out I was initially building the VM with a linux laptop and scp-ed ./result over to the mac.
Taking a [quick look into flake.nix](https://github.com/nix-community/nixos-generators/blob/master/flake.nix#L50) I see that x86_64-darwin is supported but aarch64-darwin is not. I tried adding aarch64-darwin there but didn't make much progress.
Am I missing something obvious, and would it be feasible to add this support in?

**Comment by Mic92** [comment]
I think you need to choose the `aarch64-linux` output and have a `aarch64-linux` remote builder (maybe running in a VM). I don't think you can build nixos closures on macOS otherwise. You can use the `nixosGenerate` function for that: https://github.com/Mic92/dotfiles/blob/master/nixos/images/default.nix#L40

**Comment by supermarin** [comment]
@Mic92 thanks, I'm using [`nixosGenerate`](https://github.com/supermarin/dotfiles/blob/main/nixos/flake.nix#L17) but not sure [how to pass in a remote builder option](https://github.com/nix-community/nixos-generators/blob/41f3518bc194389df22a3d198215eae75e6b5ab9/flake.nix#L29).
Is there a way to use a remote builder with `nix build` CLI that I'm missing?

**Comment by Mic92** [comment]
This is an example for [nix-ld](https://github.com/Mic92/nix-ld)

```
nix build --builders 'ssh-ng://nix@yasmin.dse.in.tum.de aarch64-linux /run/secrets/id_buildfarm 224 1 big-parallel,kvm,nixos-test - -' .#packages.aarch64-linux.nix-ld
```

` /run/secrets/id_buildfarm` is my private ssh key and `ssh-ng://nix@yasmin.dse.in.tum.de` my aarch64 builder.

**Comment by supermarin** [comment]
Wasn't aware of the `--builders` flag and have been looking for something like this! `nix help build` man page doesn't list the option. Where is this documented?

**Comment by Mic92** [comment]
These types of option are documented here: https://nixos.org/manual/nix/stable/command-ref/conf-file.html

**Comment by supermarin** [comment]
@Mic92 that's ... the last place I'd be looking for it, and it's poorly documented at best.

Is there a reason this CLI flag is not referenced in man pages?
I was initially looking [in here](https://github.com/NixOS/nix/blob/master/src/nix/build.md) but it's not clear to me how the man pages are generated/organized without spending significant amount of time.

**Comment by Mic92** [comment]
Because it's actually a nix configuration and not a command line flag:

>   You  can override settings on the command line using the --option flag,
  e.g. --option keep-outputs false. Every configuration setting also  has
  a corresponding command line flag, e.g. --max-jobs 16; for Boolean set‐
  tings, there are two flags to  enable  or  disable  the  setting  (e.g.
  --keep-failed and --no-keep-failed).

I am closing this, because this is no longer in scope of nixos-generators.

**Comment by StarryFire** [comment]
This doesn't work. I am trying to build the image on MacOS M1 and I have tried using remote builders.
The build keeps failing with the following errors:
```
error: builder for '/nix/store/9w32pkf489g3bg7iqddinfz0fblfsw28-NetworkManager.conf.drv' failed with exit code 1
error: builder for '/nix/store/c778jrnm9h4k5i9cdjj1yllmk804jpzy-append-initrd-secrets.drv' failed with exit code 1
error: builder for '/nix/store/ixvdd6zbpmn2bfqwfk5qfhj8c1mrq7mq-loopback.cfg.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/15zj82j4ajwa6ixam72hby2cf8d044qa-nixos-25.05.20250321.94c4dbe-x86_64-linux.iso.drv' failed to build
```
