### ISSUE TITLE
Messed up filename with install-iso

### ISSUE THREAD

**Issue by n8henrie** [nix-community/nixos-generators#190]
I'm currently building a pretty simple flake with the `install-iso`. The output filename is a bit of a mess:

```console
$ ls result/iso
nixos-22.11.20221118.52b2ac8-x86_64-linux.isonixos.isorescue.iso
```

I think the only relevant part of `configuration.nix` is `isoImage.isoName = "rescue.iso";` and I expected the resulting image to be just that. Before setting that value, the default resulting filename was `nixos-22.11.20221118.52b2ac8-x86_64-linux.isonixos.iso`.

The flake:

```
{
  description = "NixOS-based rescue drive";
  inputs = {
    nixpkgs.url = "nixpkgs/nixos-unstable";
    nixos-generators = {
      url = "github:nix-community/nixos-generators";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
  outputs = { self, nixpkgs, nixos-generators, ... }: {
    packages.x86_64-linux = rec {
      default = rescue;
      rescue = nixos-generators.nixosGenerate {
        system = "x86_64-linux";
        format = "install-iso";
        modules = [
          ./configuration.nix
        ];
      };
    };
  };
}
```

**Comment by Lassulus** [comment]
seems like something merged the strings rather than replacing it. what does `isoImage.isoName = lib.mkForce "rescue.iso";` do?

**Comment by n8henrie** [comment]
`lib.mkForce` results in an image name as expected (`rescue.iso`).

**Comment by quinn-dougherty** [comment]
it currently appears that `result` is a symlink to the iso itself, not to a directory containing it 

```
lrwxrwxrwx 1 qd users 93 Nov 29 20:19 result -> /nix/store/vim6sifpamh64hfqcxd5542fxk476vd9-nixos-24.05.20231127.8cfef69-x86_64-linux.iso.iso
```

**Comment by n8henrie** [comment]
It sounds like `lib.mkForce` is the recommended solution: https://github.com/nix-community/nixos-generators/pull/233#issuecomment-1567982788

Thanks for responses!
