### ISSUE TITLE
Cross-Build on Non-NixOS

### ISSUE THREAD

**Issue by sad-goldfish** [nix-community/nixos-generators#219]
To cross-build, the readme says that the configuration below should be set:
```
{
  # Enable binfmt emulation of aarch64-linux.
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];
}
```
Is there a way to set this when running `nixos-generators` from non-nixos with `nix-shell`? I believe that, without this, errors like the one below are caused:
```
error: a 'aarch64-linux' with features {} is required to build '/nix/store/2fg4ba42fbcgpsip1haqaacq94krgm9p-loopback.cfg.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, nixos-test}
```

**Comment by Lassulus** [comment]
hmm, I guess there needs to be more setup on the host system than can be done in a simple nix-shell? the nixos module to setup binfmt activates some systemd and does some other stuff. https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/binfmt.nix

**Comment by sad-goldfish** [comment]
Binfmt is (or at least, should be) set up on this system. I don't know if this is something `nixos-generators` can do (as opposed to NixOS) but ideally there would be a way to override/force this after manually doing the setup on the host system.

**Comment by sad-goldfish** [comment]
It seems to be sufficient to do `echo extra-platforms = aarch64-linux >> /etc/nix/nix.conf` and make binfmt_misc available. If building inside a container, qemu needs to be available inside the container.
