### ISSUE TITLE
The tar archive format is not supported. Supported formats are: GNU and OLDGNU.

### ISSUE THREAD

**Issue by tartavull** [nix-community/nixos-generators#221]
When trying to create an image in google cloud platform I get the following error
```
> gcloud compute images create "image-nixos" --source-uri "gs://openmind-vision/images/nixos-image-22.11.20230325.83607da-x86_64-linux.raw.tar.gz" --family="nixos-image-22-11" 

ERROR: (gcloud.compute.images.create) Could not fetch resource:
 - The tar archive format is not supported. Supported formats are: GNU and OLDGNU.
 ```
is there a way to specify the tar format being used?

**Comment by Lassulus** [comment]
hmm, I cannot reproduce this, can you post more infos? like the output of nix-info, your configuration and what commmand you ran?

**Comment by tartavull** [comment]
When I uploaded it from my machine, the mine type is x-tar, but when it gets uploaded from a GitHub Action, it becomes gzip. And this other mime type is causing the image to fail to build.
It's safe to say is unrelated to nixos-generators. Thank you!
