### ISSUE TITLE
kexec currently broken

### ISSUE THREAD

**Issue by benaryorg** [nix-community/nixos-generators#259]
The kexec and kexec-bundle formats were considered broken in #241:

> move some broken formats to `./formats-broken` to fix later

As far as I understand it's because some [kexec code living outside this repository](https://github.com/cleverca22/nix-tests/tree/master/kexec) still uses `<nixpkgs>` syntax or similar which is broken in flake evaluation or something like that.
Either way this is the tracking issue for kexec and kexec-bundle which are very useful for installing NixOS on some remote server hardware which does not offer corresponding working rescue systems.

**Comment by Lassulus** [comment]
trying to fix it in https://github.com/nix-community/nixos-generators/pull/261 but it's not ready yet

**Comment by liamdiprose** [comment]
Can this be closed now? https://github.com/nix-community/nixos-generators/commit/4d0bc031cc7d4b91cee33d75f48d5ef16209e070

**Comment by Lassulus** [comment]
I think so
