### ISSUE TITLE
Not using system.stateVersion to build

### ISSUE THREAD

**Issue by mikkel1156** [nix-community/nixos-generators#264]
My configurations system.stateVersion is not being used so it's building the image as 23.11 (unstable) which is not desirable.
nixos-generators is from 23.05 nix packages. The channels inside the image is unstable.

Might be related to #247

**Comment by Lassulus** [comment]
uhm, not sure I understand the issue. stateVersion is not used to specify which channel should be used but it's used to define which state your system was installed on.

Depending on how you use nixos-generators to build your system, there are different ways to specify the used channel. for example with the cli:

`./nixos-generate -I nixpkgs=channel:nixos-23.05 -f vm-nogui --run`

with flakes you would specify it in your flake inputs:

`inputs.nixpkgs.url = github:nixos/nixpkgs/nixos-23.05;`

**Comment by mikkel1156** [comment]
It just seems unintuitive for it to pick unstable, since what I want from NixOS is the stability, or knowing what exactly it's going to use.

I thought it would default to the channel of your own nix system. Maybe needs to be in the docs more explicitly.

Thanks for clarifying!
