### ISSUE TITLE
what happens if filesystems are defined

### ISSUE THREAD

**Issue by xiro-codes** [nix-community/nixos-generators#278]
are they just ignored in the install iso. should i force them to an empty attrs in the iso specif config

**Comment by quinn-dougherty** [comment]
[Lassalus and Tlater answer this question on discourse](https://discourse.nixos.org/t/why-can-nixos-generators-not-worry-about-hardware-configuration-nix/36187).

**Comment by SuibianP** [comment]
FWIW `iso` build artifact attempts (and of course fails) to mount host `hardware-configuration.nix` partition UUIDs.
