### ISSUE TITLE
Format raw/qcow autoResize not supported for fsType auto

### ISSUE THREAD

**Issue by cgmcintyr** [nix-community/nixos-generators#28]
Hi,

Firstly thank you for creating this repo, it's incredibly useful!

I'm running into an issue where calling either `nixos-generate -f raw` or `nixos-generate -f qcow` result in the following error:

```
error:
Failed assertions:
- Mountpoint '/': 'autoResize = true' is not supported for 'fsType = "auto"': fsType has to be explicitly set and only the ext filesystems and f2fs support it.
(use '--show-trace' to show detailed location information)
```

Is there anyway I could fix this?

**Comment by zimbatm** [comment]
it seems to have been introduced by https://github.com/NixOS/nixpkgs/commit/0eb6d0735f599fa84e99b727c93681bcae96c845

`NIX_PATH=nixpkgs=channel:nixos-19.03 ./nixos-generate -f raw` is working fine

**Comment by zimbatm** [comment]
the latest version should work with master again

**Comment by cgmcintyr** [comment]
Okay, thank you :)
