### ISSUE TITLE
Proxmox VMA image fails to import

### ISSUE THREAD

**Issue by b-** [nix-community/nixos-generators#287]
I'm attempting to build images for Proxmox using [my fork](https://github.com/b-/nixos-image) of [@physics-enthusiast's nixos-image](https://github.com/physics-enthusiast/nixos-image) repository — it's really just a very barebones `configuration.nix` and a GitHub Actions workflow that runs `nix run github:nix-community/nixos-generators -- -f ${{ matrix.format}} -c ./configuration.nix -o $PWD/result -I nixpkgs=channel:nixos-unstable` for a handful of `${{ matrix.format}}`s. I added `proxmox` to the list, hoping to get a usable image.

It generated a `vma` (or more specifically, a `vma.zst`) as expected, but upon uploading that to my Proxmox server and running `sudo qmrestore nixos.vma.zst <vmid> --storage <mystorage>` I just get an error and a blank/empty VM. The error is no different whether I decompress the `vma` first:

```shellsession
root@macpro:/zssd/dump# qmrestore nixos.vma.zst 1234 -storage zssd
error before or during data restore, some or all disks were not completely restored. VM 1234 state is NOT cleaned up.
ERROR: couldn't determine archive info from '/zssd/dump/nixos.vma.zst'

root@macpro:/zssd/dump# ls
nixos.vma.zst

root@macpro:/zssd/dump# unzstd nixos.vma.zst
nixos.vma.zst       : 1620863488 bytes

root@macpro:/zssd/dump# ls
nixos.vma  nixos.vma.zst

root@macpro:/zssd/dump# qmrestore nixos.vma 1235 -storage zssd
error before or during data restore, some or all disks were not completely restored. VM 1235 state is NOT cleaned up.
ERROR: couldn't determine archive info from '/zssd/dump/nixos.vma'
```

I also attempted to restore from the web UI, but that just didn't do anything (not even an error).

I've never worked with the VMA format before, but since it's basically Proxmox's internal backup format my guess is that maybe something about its format has changed that nixos-generators isn't aware of?

It's also possible that I'm doing something wrong, as this is the first time I'm using nixos-generators as well, but I can't imagine what it would be. I'm not setting any of the Proxmox options (the [`configuration.nix`](https://github.com/b-/nixos-image/blob/main/configuration.nix) is extremely bare) but the `nixos-generators` source leads me to believe that all of the "required" options have defaults, and I'm manually specifying a VMID and a target storage, so neither of those should matter…

**Comment by physics-enthusiast** [comment]
This might be an upstream issue since ```nixos-generator```'s proxmox [format](https://github.com/nix-community/nixos-generators/blob/master/formats/proxmox.nix) just pulls directly from ```nixpkgs```'s [proxmox-image.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/proxmox-image.nix).

**Comment by physics-enthusiast** [comment]
Upon further research it appears that it could just be a file [naming issue](https://forum.proxmox.com/threads/error-couldnt-determine-format-and-compression-type.70084/) based on the error message of the uncompressed VMA file. Maybe try adding ```vzdump-qemu-``` to the front of the filename?

**Comment by b-** [comment]
I'll try renaming it this evening and get back to you. Thank you!

**Comment by b-** [comment]
@physics-enthusiast that was the problem, yeah! Thanks! There were minor errors probably relating to some changes in accepted parameters or something, but I don't think this is a big deal:

```shellsession
root@macpro:/zssd/dump# qmrestore zssd-files:backup/vzdump-qemu-nixos.vma.zst 123457 -storage zssd
restore vma archive: zstd -q -d -c /zssd/dump/vzdump-qemu-nixos.vma.zst | vma extract -v -r /var/tmp/vzdumptmp2166189.fifo - /var/tmp/vzdumptmp2166189
CFG: size: 356 name: qemu-server.conf
DEV: dev_id=1 size: 3082813440 devname: drive-virtio0
CTIME: Sat Feb  3 15:10:31 2024
new volume ID is 'zssd:vm-123457-disk-0'
map 'drive-virtio0' to '/dev/zvol/zssd/vm-123457-disk-0' (write zeros = 0)
progress 1% (read 30867456 bytes, duration 0 sec)
progress 2% (read 61669376 bytes, duration 0 sec)
progress 3% (read 92536832 bytes, duration 0 sec)
progress 4% (read 123338752 bytes, duration 0 sec)
progress 5% (read 154140672 bytes, duration 0 sec)
progress 6% (read 185008128 bytes, duration 0 sec)
progress 7% (read 215810048 bytes, duration 0 sec)
progress 8% (read 246677504 bytes, duration 0 sec)
progress 9% (read 277479424 bytes, duration 1 sec)
progress 10% (read 308281344 bytes, duration 1 sec)
progress 11% (read 339148800 bytes, duration 1 sec)
progress 12% (read 369950720 bytes, duration 1 sec)
progress 13% (read 400818176 bytes, duration 1 sec)
progress 14% (read 431620096 bytes, duration 1 sec)
progress 15% (read 462422016 bytes, duration 1 sec)
progress 16% (read 493289472 bytes, duration 1 sec)
progress 17% (read 524091392 bytes, duration 1 sec)
progress 18% (read 554958848 bytes, duration 1 sec)
progress 19% (read 585760768 bytes, duration 1 sec)
progress 20% (read 616562688 bytes, duration 1 sec)
progress 21% (read 647430144 bytes, duration 1 sec)
progress 22% (read 678232064 bytes, duration 1 sec)
progress 23% (read 709099520 bytes, duration 2 sec)
progress 24% (read 739901440 bytes, duration 2 sec)
progress 25% (read 770703360 bytes, duration 2 sec)
progress 26% (read 801570816 bytes, duration 2 sec)
progress 27% (read 832372736 bytes, duration 2 sec)
progress 28% (read 863240192 bytes, duration 2 sec)
progress 29% (read 894042112 bytes, duration 2 sec)
progress 30% (read 924844032 bytes, duration 2 sec)
progress 31% (read 955711488 bytes, duration 2 sec)
progress 32% (read 986513408 bytes, duration 2 sec)
progress 33% (read 1017380864 bytes, duration 2 sec)
progress 34% (read 1048182784 bytes, duration 3 sec)
progress 35% (read 1078984704 bytes, duration 3 sec)
progress 36% (read 1109852160 bytes, duration 3 sec)
progress 37% (read 1140654080 bytes, duration 3 sec)
progress 38% (read 1171521536 bytes, duration 3 sec)
progress 39% (read 1202323456 bytes, duration 3 sec)
progress 40% (read 1233125376 bytes, duration 3 sec)
progress 41% (read 1263992832 bytes, duration 3 sec)
progress 42% (read 1294794752 bytes, duration 3 sec)
progress 43% (read 1325662208 bytes, duration 3 sec)
progress 44% (read 1356464128 bytes, duration 3 sec)
progress 45% (read 1387266048 bytes, duration 3 sec)
progress 46% (read 1418133504 bytes, duration 3 sec)
progress 47% (read 1448935424 bytes, duration 3 sec)
progress 48% (read 1479802880 bytes, duration 3 sec)
progress 49% (read 1510604800 bytes, duration 3 sec)
progress 50% (read 1541406720 bytes, duration 3 sec)
progress 51% (read 1572274176 bytes, duration 3 sec)
progress 52% (read 1603076096 bytes, duration 3 sec)
progress 53% (read 1633943552 bytes, duration 3 sec)
progress 54% (read 1664745472 bytes, duration 3 sec)
progress 55% (read 1695547392 bytes, duration 3 sec)
progress 56% (read 1726414848 bytes, duration 3 sec)
progress 57% (read 1757216768 bytes, duration 3 sec)
progress 58% (read 1788084224 bytes, duration 3 sec)
progress 59% (read 1818886144 bytes, duration 3 sec)
progress 60% (read 1849688064 bytes, duration 3 sec)
progress 61% (read 1880555520 bytes, duration 3 sec)
progress 62% (read 1911357440 bytes, duration 3 sec)
progress 63% (read 1942224896 bytes, duration 3 sec)
progress 64% (read 1973026816 bytes, duration 3 sec)
progress 65% (read 2003828736 bytes, duration 3 sec)
progress 66% (read 2034696192 bytes, duration 3 sec)
progress 67% (read 2065498112 bytes, duration 3 sec)
progress 68% (read 2096365568 bytes, duration 3 sec)
progress 69% (read 2127167488 bytes, duration 3 sec)
progress 70% (read 2157969408 bytes, duration 3 sec)
progress 71% (read 2188836864 bytes, duration 3 sec)
progress 72% (read 2219638784 bytes, duration 4 sec)
progress 73% (read 2250506240 bytes, duration 4 sec)
progress 74% (read 2281308160 bytes, duration 4 sec)
progress 75% (read 2312110080 bytes, duration 4 sec)
progress 76% (read 2342977536 bytes, duration 4 sec)
progress 77% (read 2373779456 bytes, duration 4 sec)
progress 78% (read 2404646912 bytes, duration 4 sec)
progress 79% (read 2435448832 bytes, duration 4 sec)
progress 80% (read 2466250752 bytes, duration 4 sec)
progress 81% (read 2497118208 bytes, duration 4 sec)
progress 82% (read 2527920128 bytes, duration 4 sec)
progress 83% (read 2558787584 bytes, duration 4 sec)
progress 84% (read 2589589504 bytes, duration 4 sec)
progress 85% (read 2620391424 bytes, duration 4 sec)
progress 86% (read 2651258880 bytes, duration 5 sec)
progress 87% (read 2682060800 bytes, duration 5 sec)
progress 88% (read 2712928256 bytes, duration 5 sec)
progress 89% (read 2743730176 bytes, duration 5 sec)
progress 90% (read 2774532096 bytes, duration 5 sec)
progress 91% (read 2805399552 bytes, duration 5 sec)
progress 92% (read 2836201472 bytes, duration 5 sec)
progress 93% (read 2867068928 bytes, duration 5 sec)
progress 94% (read 2897870848 bytes, duration 5 sec)
progress 95% (read 2928672768 bytes, duration 5 sec)
progress 96% (read 2959540224 bytes, duration 5 sec)
progress 97% (read 2990342144 bytes, duration 5 sec)
progress 98% (read 3021209600 bytes, duration 5 sec)
progress 99% (read 3052011520 bytes, duration 5 sec)
progress 100% (read 3082813440 bytes, duration 5 sec)
total bytes read 3082813440, sparse bytes 1462378496 (47.4%)
space reduction due to 4K zero blocks 0.215%
vm 123457 - unable to parse config: additionalSpace: 512M
vm 123457 - unable to parse config: bootSize: 256M
vm 123457 - unable to parse config: diskSize: auto
rescan volumes...
VM 123457 (virtio0): size of disk 'zssd:vm-123457-disk-0' updated from 0T to 2940M
root@macpro:/zssd/dump#
```

I'm hesitant to close this issue, because I think this is still an issue with the documentation. I'd just make a documentation change myself, but I'm not sure where that (filename has to start with `vzdump-qemu-`) should go.

**Comment by b-** [comment]
Actually, is there a way that a generated Proxmox image could just automatically have `vzdump-qemu-` prepended to the filename? That would solve this issue, I think.

@physics-enthusiast should I open a related issue in your nixos-image repo about the Proxmox vma not being named `vzdump-qemu-whatever.vma.zst`?

**Comment by b-** [comment]
> > I'm hesitant to close this issue, because I think this is still an issue with the documentation. I'd just make a documentation change myself, but I'm not sure where that (filename has to start with `vzdump-qemu-`) should go.
> 
> Oh that was an issue on my end since I was auto-renaming the files. The files coming out of nixos-generators are correctly named. I've since switched to putting the images in a compressed 7z archive (see my rationale [here](https://github.com/physics-enthusiast/nixos-image?tab=readme-ov-file#release-file-naming-scheme)) and added the proxmox and proxmox-lxc formats to the main repo. Do try it out and feel free to open an issue on nixos-image if it still doesn't work. In either case, I think it's safe to close this issue since it's not a problem with nixos-generators. You can also raise an issue with the proxmox maintainers if you believe the documentation was unclear on the naming scheme (googling "proxmox vma naming", it seems that you're not the only one), but I'm not familiar enough with the project and it's contribution guidelines to advise you on this or judge if it was user error or truly incomplete documentation.

Thanks so much for the very thorough explanation, that helps so much. I didn't realize nixos-generators was renaming the image (and I guess I didn't bother to check, since I didn't think it was a filename issue when I was looking at the code!) 

I'll close this then, and at least at a glance nixos-image looks like it's good — I'll open an issue there if I have an issue with it.

**Comment by physics-enthusiast** [comment]
> Thanks so much for the very thorough explanation, that helps so much. I didn't realize nixos-generators was renaming the image 

No problem! Just one final clarification, *nixos-image* is the one doing the renaming, not nixos-generators (which is why I suggested closing this issue).

**Comment by b-** [comment]
> > Thanks so much for the very thorough explanation, that helps so much. I didn't realize nixos-generators was renaming the image
> 
> No problem! Just one final clarification, _nixos-image_ is the one doing the renaming, not nixos-generators (which is why I suggested closing this issue).

Understood, that's indeed why I closed it — I definitely trust your word on nixos-image's behavior! :)
