### ISSUE TITLE
Looking for an example.

### ISSUE THREAD

**Issue by cjemorton** [nix-community/nixos-generators#299]
Looking for an example on how to generate a Oracle Cloud oci compatible image with basic options as slim as possible, for both the Ampere and the Amd64 services.

**Comment by mausch** [comment]
Hey, Oracle can import VMDK and QCOW2, have you tried that route as a workaround?

**Comment by Mic92** [comment]
I assume @mausch was the answer.
Otherwise nixos-anywhere also works with oracle cloud.
