### ISSUE TITLE
virtualisation.disksize is null

### ISSUE THREAD

**Issue by Bert-Proesmans** [nix-community/nixos-generators#306]
Since https://github.com/nix-community/nixos-generators/commit/4c7b914d1f7c48c87b5d64868e9d2d4f1b7a0db5 my format builds break. The issue being that "null" is not a valid value for the qemu disk generation script here; https://github.com/NixOS/nixpkgs/blob/nixos-23.11/nixos/modules/virtualisation/qemu-vm.nix#L124

How to reproduce the issue;
1. Add nixos-generators as flake input
2. Create attribute `machine` which value is a nixosSystem with basic config and imported module `inputs.nixos-generators.nixosModules.all-formats`
3. Build format output `.#machine.config.formats.vm`
4. Execute ./result

Expected;
Output builds, produces ./result. Running ./result will launch qemu booting the machine.

Actual;
The script that launches qemu fails on disk creation, reporting an error that "M" is not a valid disksize.

This issue was introduced by the following lines of code; https://github.com/nix-community/nixos-generators/blob/4c7b914d1f7c48c87b5d64868e9d2d4f1b7a0db5/formats/vm.nix#L13-L15

null is a valid value, according to the typechecks of `virtualisation.disksize`, but actually isn't looking at the script that applies its value.
the code worked before because `virtualisation.disksize` was not explicitly set before, falling back to default value 1024.  
In any case is the implemented approach not composable. I'm not fully aware of all applications of the value "auto", but for this specific case I'm very certain the nixos option assignment could and should be reworked into the snippet below to comply with nix common coding practise;
```nix
virtualisation.diskSize = lib.mkIf (diskSize != "auto")  lib.strings.toIntBase10 diskSize;
```

**Comment by Lassulus** [comment]
ah, can you open a PR to fix that issue?

**Comment by Bert-Proesmans** [comment]
ofcourse! I would have done so in the first place if I had more certainty knowing full context around these options. As you can see above I also created an issue on the nixpkgs repo to get more information about nullability.
