### ISSUE TITLE
Add option to specify nixpkgs path or channel

### ISSUE THREAD

**Issue by davidak** [nix-community/nixos-generators#31]
I need nixpkgs with a patch, so this feature whould be useful!

Or can i already use an env var? Then, please document it.

Currently, i use nix-build like this:
`
[davidak@ethmoid:~/code/nixpkgs/nixos]$ time nix-build /home/davidak/code/nixpkgs/nixos -A config.system.build.isoImage -I nixos-config=/home/davidak/code/nixos-config-greenbone/machines/targets-image/configuration.nix default.nix`

**Comment by zimbatm** [comment]
Fixed in e6578895b5961596a8e651d0c0222fbb4c6c73b5. You can now pass `-I nixpkgs=/path/to/nixpkgs` like on a nix-build command.

**Comment by zimbatm** [comment]
before that you could already do that with `NIX_PATH=nixpkgs=/path/to/nixpkgs nixos-generate ...`

**Comment by davidak** [comment]
Perfect. Thanks for the fast fix!

Now i can just specify my unmerged PR branch to build the image:

`nixos-generate -I nixpkgs=https://api.github.com/repos/davidak/nixpkgs/tarball/backport_nixos-containers-TimeoutStartSec -c /home/davidak/code/nixos-config-greenbone/machines/targets-image/configuration.nix -f iso`
