### ISSUE TITLE
modified date

### ISSUE THREAD

**Issue by ShalokShalom** [nix-community/nixos-generators#313]
Hi there :)

Your generated images do maintain a wrong "modified date" and that leads to them being sorted incorrectly in my file manager. 

![Screenshot_20240310_110022-1](https://github.com/nix-community/nixos-generators/assets/6344099/dc63a62e-2e43-4711-aedf-77572801e250)

![Screenshot_20240310_110414](https://github.com/nix-community/nixos-generators/assets/6344099/0751d04f-b9af-4162-bdf7-fcabc1ee8cc0)

**Comment by Lassulus** [comment]
ah thats a feature of nix, so thats expected :)

**Comment by ShalokShalom** [comment]
Feature? Are you joking? 😄

**Comment by Lassulus** [comment]
from https://nixos.org/manual/nix/stable/language/derivations.html

```
After the build, Nix sets the last-modified timestamp on all files in the build result to 1 (00:00:01 1/1/1970 UTC), sets the group to the default group, and sets the mode of the file to 0444 or 0555 (i.e., read-only, with execute permission enabled if the file was originally executable). Note that possible setuid and setgid bits are cleared. Setuid and setgid programs are not currently supported by Nix. This is because the Nix archives used in deployment have no concept of ownership information, and because it makes the build result dependent on the user performing the build.
```
