### ISSUE TITLE
confusing readme

### ISSUE THREAD

**Issue by tcurdt** [nix-community/nixos-generators#321]
Maybe it's the newbie - but I don't find the readme particular clear. I have my system setup

```
  outputs =
    { self
    # ...
    , ... } @ inputs:
    {
      nixosConfigurations = {
        utm = import ./machines/utm.nix {
```

Now the readme shows

```
      packages.x86_64-linux = {
        iso = nixos-generators.nixosGenerate {
```
but I am not sure how to reference the `nixosConfiguration` I want to build.

Further below there is

```
      nixosModules.my-machine = { config, ... }: {
        imports = [
          nixos-generators.nixosModules.all-formats
        ];

        nixosConfigurations.my-machine = nixpkgs.lib.nixosSystem {
          modules = [ self.nixosModules.my-machine ];
        };
```

Which seems the `nixosConfiguration` needs to be wrapped to generate format?

**Comment by Lassulus** [comment]
seems like nixosConfigurations is misaligned, it should not be inside nixosModules but on the same level

**Comment by tcurdt** [comment]
So it should be

```
nixosModules.my-machine = { config, ... }: {
  imports = [
    nixos-generators.nixosModules.all-formats
  ];

  nixpkgs.hostPlatform = "x86_64-linux";
};

nixosConfigurations.my-machine = nixpkgs.lib.nixosSystem {
  modules = [ self.nixosModules.my-machine ];
};
```

Is there also a way to turn the reference around? More like this?

```
nixosModules.my-machine = { config, ... }: {
  imports = [
    nixos-generators.nixosModules.all-formats
  ];

  # reference self.nixosConfigurations.my-machine
};

nixosConfigurations.my-machine = nixpkgs.lib.nixosSystem {
  modules = [
    {
      nixpkgs.hostPlatform = "x86_64-linux";
    }
  ];
};
```

**Comment by Lassulus** [comment]
not really, nixosConfigurations are instantiated modules, so there is no good way to get the config back out of them without having a bunch of conflicts.

**Comment by tcurdt** [comment]
Hm. That's unfortunate. 🤔

`nixosConfigurations` has been my definition of the machine so far.
So I would need to restructure this the moment I want to pack it up into e.g. an iso?

Or could it be an option to always see the `nixosModule` as the "base machine unit".
And then have the image generation just be an optional feature - somehow?

**Comment by Lassulus** [comment]
ah, you can generate an iso out of a nixosConfiguration. you can just add `imports = [ nixos-generators.nixosModules.all-formats ];`

later you can do something like packages.x86_64-linux.myIso = self.nixosConfigurations.myMachine.formats.iso

**Comment by tcurdt** [comment]
Ah, like this?

```
  nixosConfigurations = {
    utm = import ./machines/utm.nix {
      hostName = "nixos";
      hostPlatform = "aarch64-linux";
      nixpkgs = nixpkgs-unstable;
      home-manager = home-manager-unstable;
      inherit impermanence;
      inherit nixos-generators;
      inherit release-go;
    };

  packages.x86_64-linux.myiso = self.nixosConfigurations.utm.formats.iso;
```


utm.nix:
```
{ nixpkgs, nixos-generators, impermanence, hostName, hostPlatform, ... } @ inputs: let

  hardware = "utm";
  pkgs = nixpkgs.legacyPackages.${hostPlatform};
  imports = [ nixos-generators.nixosModules.all-formats ];

in nixpkgs.lib.nixosSystem {
  specialArgs = { inherit inputs; };
  modules = [
```

But that gives:

```
 error: attribute 'formats' missing
 at /nix/store/03rgacr166c3r7d9gpjd9rkgslyfmwqc-source/flake.nix:65:37:
     64|
     65|       packages.x86_64-linux.myiso = self.nixosConfigurations.utm.formats.iso;
       |                                     ^
     66|
```

I guess something is wrong with the import?

The full code of my little nix playground [is here](https://github.com/tcurdt/nixcfg).

**Comment by Lassulus** [comment]
ah, my bad. there is .config missing:
```
self.nixosConfigurations.utm.config.formats.iso;
```

**Comment by tcurdt** [comment]
Hmmm.

```
       error: attribute 'formats' missing
       at /nix/store/7lyql3apyya096p0knd60iqvr1kpjbkf-source/flake.nix:65:37:
           64|
           65|       packages.x86_64-linux.myiso = self.nixosConfigurations.utm.config.formats.iso;
```

**Comment by Lassulus** [comment]
where is the imports from your let in utm.nix used? the utm.nix is cut off

**Comment by Lassulus** [comment]
ah, yeah that imports is not referenced in the in, you can just add it into the modules list instead. like:
```

modules = [
  ....
  nixos-generators.nixosModules.all-formats
  ....
]
```

**Comment by tcurdt** [comment]
Ah! Fantastic. Progress! :-)

Since I am currently trying on `aarch64-darwin` this here is kind of expected:

```
nix build .#packages.x86_64-linux.myiso                
warning: Git tree '/Users/tcurdt/Desktop/infra/deploy/nixcfg' is dirty
error: a 'aarch64-linux' with features {} is required to build '/nix/store/ly7yr41pifyadb5n618c3dr96xqp6nlf-Caddyfile.drv', but I am a 'aarch64-darwin' with features {apple-virt, benchmark, big-parallel, nixos-test}
```

Although I am surprised it tries to build `aarch64-linux` and not `x86_64-linux` as specified.

```
      packages.x86_64-linux.myiso = self.nixosConfigurations.utm.config.formats.iso;
```

I would have expected it tells me off that I cannot build `x86_64-linux` on a `aarch64-darwin` system.

**Comment by Lassulus** [comment]
yes, the system will be build in the architecture your hostPlatform is specified in. the x86 in packages is just the attribute under which you would export it in the flake but it wouldn't change the hostPlatform. In this case nix building your flake would try to build the package in the local architecture and then fail with it being in another architecture entirely :)

**Comment by tcurdt** [comment]
OK, make sense.

And I have built my first iso 🎉 (on a different machine)

```
/nix/store/is27dbzy8vj5v5jz68v97mh12fkw2nv7-nixos.iso/iso/nixos.iso
```

Thank you so much for the help!

Adding qemu looks easy from the readme - but I am sceptical :)
Again not sure where it would need to go in the my flake.

And I quess I would want
```
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];
```
only for the iso build - not the system?

**Comment by Lassulus** [comment]
binfmt you want on the system where you build the iso so you can build aarch64-linux stuff on your x86 machine.
qemu would mostly be the same, you can just put the formats.vm or formats.vm-nogui into any packages output and build or `nix run` it directly

**Comment by tcurdt** [comment]
Since I am on just nix on darwin - not nixOS for most of the time, the `boot.binfmt.emulatedSystems`I would then need to get included there somehow. But that's beyond the scope of this ticket :)

While I am fine now and the ticket could be closed - would you care for a PR for the readme?
I could try.

**Comment by Lassulus** [comment]
sure, an addition to the readme for darwin users would be nice, usually I don't test stuff on darwin to to lack of the correct hardware :)
