### ISSUE TITLE
how to add /var/ state files to install-iso image?

### ISSUE THREAD

**Issue by bam80** [nix-community/nixos-generators#335]
I need to add my `/var/lib/bluetooth` Bluetooth keys to an "install-iso" image.

As `/var` is tmpfs there, and the keys should be in place before `bluetooth` service starts,
how would adding the keys look in the .nix configuration, to generate proper .ISO image?

**Comment by Mic92** [comment]
You can use `systemd.tmpfiles.settings` to copy files at boot time https://www.freedesktop.org/software/systemd/man/latest/tmpfiles.d.html

Here is a random example I found on github: https://github.com/NickCao/flakes/blob/adfa0e4c249f196589086d184ded104b7c5a28fc/nixos/mainframe/configuration.nix#L33
