### ISSUE TITLE
Merge nixos-generators with nixpkgs

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nixos-generators#340]
nixos-generators is a small wrapper around NixOS modules.

If we could get this upstreamed, it would be better maintained, as most of the bugs posted here are actually upstream issues.

This would also open the road to having a `nixos-rebuild image --format <format>` type CLI.

What needs to happen:

1. We need a unified interface that exposes all these different image types in one place. Like a system output of NixOS.
2. Bonus: make this part of nixos-rebuild.

**Comment by Mic92** [comment]
In nix we have a bundler interface. For consistency it could have the same name but on the other hand, "image" is way more common.

**Comment by zimbatm** [comment]
@phaer is working on this. First PR is https://github.com/NixOS/nixpkgs/pull/349624

**Comment by bew** [comment]
Great news ✨
Could we keep the issue opened as a tracking issue? (or have a tracking issue in nixpkgs repo?)

**Comment by phaer** [comment]
The original PR which i then split into smaller pieces contains links to all other PRs in the description. https://github.com/NixOS/nixpkgs/pull/347275

Porting the `build-image` from `nixos-rebuild` to `nixos-rebuild-ng` isn't done yet.
