### ISSUE TITLE
What's the difference between `proxmox-lxc` and `lxc`?

### ISSUE THREAD

**Issue by muradbu** [nix-community/nixos-generators#342]
Hi, sorry I couldn't find a better place to ask this question. 

Proxmox templates already are tarballs, so I'm not sure what the technical differences are between these build outputs:

> lxc | create a tarball which is importable as an lxc container, use together with lxc-metadata
> proxmox-lxc | LXC template for proxmox

My end goal is to have NixOS guests on my Proxmox (Debian) cluster.

That's all, thanks.

**Comment by Mic92** [comment]
https://github.com/nix-community/nixos-generators/blob/master/formats/proxmox-lxc.nix

It's a different upstream nixpkgs module. Check the source code of it here: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/proxmox-lxc.nix
Here is the lxc one: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/lxc-container.nix

Looks like it is mainly about how containers receive their network configuration.
