### ISSUE TITLE
Docker not running after creating LXC in Proxmox

### ISSUE THREAD

**Issue by muradbu** [nix-community/nixos-generators#344]
Hello, I'm new to Nix. 

I generated a Proxmox LXC template from this config:

```nix
{ pkgs, config, lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/virtualisation/proxmox-lxc.nix")
  ];

  environment.systemPackages = with pkgs; [
    docker
  ]

  virtualisation.docker = {
    enable = true;
    rootless = {
      enable = true;
      setSocketVariable = true;
    };
  };

  boot.isContainer = true;
  system.stateVersion = "24.05";
}
```

From my configuration I expected Docker to be running because of the `virtualisation.docker.enable = true;` but:

```
[root@test:~]# docker ps
Cannot connect to the Docker daemon at unix:///run/user/0/docker.sock. Is the docker daemon running?
[root@test:~]# sudo systemctl start docker
[root@test:~]# docker ps
Cannot connect to the Docker daemon at unix:///run/user/0/docker.sock. Is the docker daemon running?
```

How can I ensure Docker (or other daemons for that matter) are running after creating the template?

**Comment by Mic92** [comment]
It's weird that docker tries to reach out to /run/user for a socket that is usually at /run/docker.sock. Could be some fallback though because docker is not running. Check `systemctl status docker` instead. 

I don't think this a nixos-generator issue. nixos-generator just exposes nixos image modules through a CLI, i.e. it doesn't even define the lxc module itself. For general NixOS questions, please use https://discourse.nixos.org/
Thanks!

**Comment by muradbu** [comment]
> It's weird that docker tries to reach out to /run/user for a socket that is usually at /run/docker.sock. Could be some fallback though because docker is not running. 

Could this be because I'm running Docker daemon as a non-root user ([rootless mode](https://docs.docker.com/engine/security/rootless/))?

Thanks, I will move to discourse

**Comment by Mic92** [comment]
If you run in rootless mode, I believe you need to start docker yourself. At least my last information was that the module only handles a systemd wide daemon. You might be able to start it as a systemd user service?

**Comment by monnoval** [comment]
I actually have this issue `Cannot connect to the Docker daemon at unix:///run/user/0/docker.sock` when I shutdown nixos LXC from Proxmox 8.2.x (running local-btrfs), even if I turn off all docker containers (before turning off the LXC) I still get this issue. 

I also tested on having an LXC using debian not nixos with docker and everything works fully, no issues when I shutdown and boot again.
