### ISSUE TITLE
Integration with flake-parts seems to cause an infinite recursion

### ISSUE THREAD

**Issue by Kreyren** [nix-community/nixos-generators#349]
Referencing: https://github.com/NiXium-org/NiXium/pull/118#issuecomment-2221882643

I am trying to declare the `nixosGenerator` with a workaround for https://github.com/NixOS/nixpkgs/issues/286196 as a module (so that it can be used for other things) to be able to declare it as a package (to be able to set up a CI/CD to produce the build and additional management) so that it can be declared as an app for `nix run`.

Where using `packages.aarch64-linux.nixos-tsvetan-recovery = self.inputs.nixos-generators.nixosGenerate` seems to cause an infinite recursion when used with [flake-parts](https://flake.parts), i was discussing this in NixOS room where it was suggested to be a nixos-generator bug, thus filing this issue.

**Comment by DavHau** [comment]
you put a `flake.` prefix in front of your declaration, so it becomes `flake.packages.aarch64-linux.nixos-tsvetan-recovery = ...`.

It is weird that flake parts crashes with an infinite recursion because of that. Maybe report this at flake-parts.

**Comment by Kreyren** [comment]
It causes infinite recursion even with the `flake.` prefix removed from relevant configuration [NiXium-org/NiXium@`0919224` (#118)](https://github.com/NiXium-org/NiXium/pull/118/commits/091922426de3cff3b0fe51cac1eff5734691351a)

Cross-Referencing: https://github.com/hercules-ci/flake-parts/issues/236

**Comment by DavHau** [comment]
@Kreyren the other declarations in the file also need to be prefixed with `flake.`.
I tried is yesterday and it worked

**Comment by Kreyren** [comment]
@DavHau Thanks! i made it work, it seems to trigger an infinite recursion when the option is called without a `flake` or when the option fails to evaluate.
