### ISSUE TITLE
`nix run nixpkgs.nix-info` don't work in generated ISO

### ISSUE THREAD

**Issue by davidak** [nix-community/nixos-generators#37]
```
[root@targets-host:~]# nix run nixpkgs.nix-info -c nix-info -m
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

[root@targets-host:~]# nix-channel --list
nixos https://nixos.org/channels/nixos-19.03
```

**Comment by zimbatm** [comment]
It looks like there are multiple issues with nix-info:

It fails when the channel hasn't been populated. `nix-channel --update` work around that issue.

It doesn't report the nixpkgs version that was used to build the current system. Which is what we are interested in for nixos bug reports.

**Comment by davidak** [comment]
I tried with the official installer iso. It works there.

Maybe nix-info should be installed on any NixOS installation or even be included in Nix with `nix info`? Whould that solve this issue and also when the system has no internet connection?

**Comment by zimbatm** [comment]
Actually I misread your logs. The issue here is that `nix run` is not able to find the channel and evaluate nixpkgs in the first place. That's fine, not all systems should come with a channel pre-loaded as it's quite large.

**Comment by davidak** [comment]
>That's fine, not all systems should come with a channel pre-loaded as it's quite large.

That makes sense. But it should still be possible to create useful bugreports, so nix-info should work, even in such cases.

I'll create an issue upstream since this is not a nixos-generators problem.
