### ISSUE TITLE
LXC expects /sbin/init

### ISSUE THREAD

**Issue by davidak** [nix-community/nixos-generators#40]
Follow up to https://github.com/nix-community/nixos-generators/pull/19

I have seen that `boot.loader.initScript.enable` exists and is used for systemd-nspawn to work with machinectl in https://github.com/NixOS/nixpkgs/pull/67232.

We can probably use that for our LXC image!

**Comment by asbachb** [comment]
Maybe it would be better to bake that into NixOS? Since when using lxc and you want to be able to `nixos-rebuild switch` there's a need for updating these symlinks.

**Comment by aanderse** [comment]
This has been resolved. We can close this issue now.
