### ISSUE TITLE
No space left on device when using aws, azure, or gce formats

### ISSUE THREAD

**Issue by chiroptical** [nix-community/nixos-generators#69]
I am trying to build an image appropriate for cloud deployment. I was successfully able to build an iso using `nixos-generate -f iso -c /etc/nixos/configuration.nix`. However, if I try to build one for aws, azure, or gce I get ![nixos-generate-fails](https://user-images.githubusercontent.com/3086255/92941793-d18b8780-f41e-11ea-93fb-457b6f3a1b4d.png). I have approximately 30 GB of free space on the VM.

I found the file `azure-image.nix` and I presume I need to bump `virtualisation.azureImage.diskSize` to ~10GB. Is there documentation somewhere for this?

Note: I am in the Nix/NixOS Discord as @chiroptical if you would rather discuss it there. Thanks.

**Comment by Lassulus** [comment]
hi, this is indeed an upstream issue inside nixpkgs. I currently try to patch it there. So hopefully this will soonish not be an issue anymore.

for now you can indeed set `virtualisation.azureImage.diskSize` to something like 10000 which would be 10GB. In the future the image builder should autodetect the required diskSize.

The documentation for image specific options are indeed very hidden and my way around it is always to look in the nixpkgs sourcecode, which you seem to have done also.

**Comment by chiroptical** [comment]
Thanks for the quick response. Is there an example somewhere on how to actually change it? Should I just modify it in place?

**Comment by chiroptical** [comment]
I get it now! I adjust this in `configuration.nix`. Thanks for your help @Lassulus

**Comment by d-johnston-fugro** [comment]
> hi, this is indeed an upstream issue inside nixpkgs. I currently try to patch it there. So hopefully this will soonish not be an issue anymore.
> 
> for now you can indeed set `virtualisation.azureImage.diskSize` to something like 10000 which would be 10GB. In the future the image builder should autodetect the required diskSize.
> 
> The documentation for image specific options are indeed very hidden and my way around it is always to look in the nixpkgs sourcecode, which you seem to have done also.

That option doesn't seem to exist

```
nixos-generate -c ./configuration.nix -f amazon
error: The option `virtualisation.amazonImage' does not exist. Definition values:
       - In `/home/dylanj/Workspace/fugro/spaarc.spire/configuration.nix':
           {
             diskSize = 10000;
           }
(use '--show-trace' to show detailed location information)
```

**Comment by Lassulus** [comment]
> > hi, this is indeed an upstream issue inside nixpkgs. I currently try to patch it there. So hopefully this will soonish not be an issue anymore.
> > for now you can indeed set `virtualisation.azureImage.diskSize` to something like 10000 which would be 10GB. In the future the image builder should autodetect the required diskSize.
> > The documentation for image specific options are indeed very hidden and my way around it is always to look in the nixpkgs sourcecode, which you seem to have done also.
> 
> That option doesn't seem to exist
> 
> ```
> nixos-generate -c ./configuration.nix -f amazon
> error: The option `virtualisation.amazonImage' does not exist. Definition values:
>        - In `/home/dylanj/Workspace/fugro/spaarc.spire/configuration.nix':
>            {
>              diskSize = 10000;
>            }
> (use '--show-trace' to show detailed location information)
> ```

seems like the option was renamed to `virtualisation.amazonImage.sizeMB`
https://github.com/NixOS/nixpkgs/blob/master/nixos/maintainers/scripts/ec2/amazon-image.nix#L44

**Comment by d-johnston-fugro** [comment]
Just wanted to update on the solution, turns out `/tmp` was filling up so I had to resize it.
