### ISSUE TITLE
[Feature] Flake support

### ISSUE THREAD

**Issue by cab404** [nix-community/nixos-generators#71]
It would be great to be able to generate stuff based on nix flakes.

**Comment by jD91mZM2** [comment]
Here you go: https://github.com/nix-community/nixos-generators/pull/76

**Comment by cab404** [comment]
> Here you go: #76

I kind of meant generation of systems based on flake configurations, e.g 
`nixos-generate --flake gitlab:cab404/nixos-config`

**Comment by jD91mZM2** [comment]
I think that works now, no?

**Comment by cab404** [comment]
> I think that works now, no?

Oh, from first view I thought that you just packages nixos-generators with flakes
Gonna check soon, thanks)

**Comment by asymmetric** [comment]
Should this be closed by #76?

**Comment by Lassulus** [comment]
`¯\_(ツ)_/¯` I don't use flakes yet

**Comment by asymmetric** [comment]
I do and this works :)

**Comment by cab404** [comment]
I am getting errors with that pull request though.

**Comment by asymmetric** [comment]
@cab404 the PR has been merged, so maybe you can file an issue?
