### ISSUE TITLE
Mount host `/nix/store` as guest's store

### ISSUE THREAD

**Issue by Pamplemousse** [nix-community/nixos-generators#80]
I recently heard of `nixos-generators`, and I tried to use it to build images that are meant to be ran exclusively on the host building them.

So far, I could not get any result trying to use `-f qcow`, as I always reach a `no space left on device` error after hours of building (similar to - and maybe related to - #73)...

When using `nixos-rebuild build-vm`, the resulting image (and related VM startup script) seems to mount the host's `/nix/store` (as read-only) as the store for the guest.
**Is there something similar that could be achieved here?**
As my guest will run exclusively on my host, there is no point "duplicating" the store, or building packages that are already present on the host: This could save both time and space.

Cheers,

**Comment by zimbatm** [comment]
Try one of `vm`, `vm-bootloader` or `vm-nogui` outputs. Those are already wrapping qemu to mount the `/nix/store` into the VM.

**Comment by Pamplemousse** [comment]
Right.

I ended up having it working.
Probably the `no space left on device` was due to building from `unstable` on my host, but using a local `nixpkgs` slightly desynchronised with `nixos-generators`, which induced a lot of packages being built "twice".
