### ISSUE TITLE
fsType conflict definition

### ISSUE THREAD

**Issue by DblK** [nix-community/nixos-generators#82]
When I ran the command `nixos-generate -f openstack -c configuration.nix` I have the following error:

```sh
error: The option `fileSystems./.fsType' has conflicting definition values:
- In `/nix/store/pnnffbr69z7p33p39bpyvn8xnc4v63ls-nixos-generators/share/nixos-generator/formats/raw.nix': "ext4"
- In `/nix/var/nix/profiles/per-user/root/channels/nixpkgs/nixos/m
```

Inside my `configuration.nix` I had the following line:
```sh
imports = [ <nixpkgs/nixos/modules/installer/cd-dvd/installation-cd-minimal.nix> ];
```
Which seems to be the root cause of the issue. Will it be safe to remove it?

Note that I had the same issue with `qcow` and `raw`.
Since I am new to nixos I do not know if it's normal or not and how to bypass this issue.

**Comment by Lassulus** [comment]
you can remove the import from your configuration. An equivalent (but conflicting import) is happening inside the openstack format: https://github.com/nix-community/nixos-generators/blob/master/formats/openstack.nix#L4
