### ISSUE TITLE
A 'x86_64-linux' with features {kvm} is required to build...

### ISSUE THREAD

**Issue by DblK** [nix-community/nixos-generators#83]
I have a basic `config.nix` as follow:

```sh
{ config, pkgs, ... }:

{
  boot.kernelModules = [ "kvm-amd" "kvm-intel" ];

  environment.systemPackages = with pkgs; [
    cloud-init
    iptables
    qemu

    docker_18_09
  ];

  users.users.root.password = "nixos";

  services = {
    xserver = {
      videoDrivers = [ "qxl" ];
    };

    qemuGuest = {
      enable = true;
    };

    cloud-init = {
      enable = true;
    };

    openssh = {
        enable = true;
    };
  };
}
```

And when I run `nixos-generate -f qcow -c configuration.nix` I have the following error:

```sh
error: a 'x86_64-linux' with features {kvm} is required to build '/nix/store/8lv9iwhsn0jpxcirnq1kgbagvvvk5m2x-nixos-disk-image.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, nixos-test}
```

I am using `nixos/nix` docker to build the os if it matters.
Any help would be appreciated :)

PS: My goal is to make a `qcow` image with `ssh`, `cloud-init`, `docker` and `qemu-agent` to be used with proxmox.

**Comment by Lassulus** [comment]
ah, nixos generally uses VMs to build all the images nixos-generators gives you. So this is more of a nixos problem and I'm actually not sure if (and how) you can enable KVM inside the docker container. Theoretically it should be possible, since kvm should run inside the container. 

from the manual I find this line. so maybe you just need to install qemu-kvm inside the container?
```
By default, system-features includes kvm if /dev/kvm exists. For compatibility, it also includes the pseudo-features nixos-test, benchmark and big-parallel which are used by Nixpkgs to route builds to particular Hydra build machines.
```

**Comment by DblK** [comment]
I just setup an `ubuntu 20.4` machine and installed `nixos` and `nixos-generators` on it.
I was facing the same issue.
After doing `sudo apt-get install qemu-kvm` the issue is still there

Any idea?

**Comment by Lassulus** [comment]
uhm, does /dev/kvm exist on it?

**Comment by DblK** [comment]
I just launch `kvm-ok` and it says `INFO: Your CPU does not support KVM extensions`.
For your information is a VM so it might be normal.
I will dig more info about it. Thanks for your reply ;)

**Comment by lincoln-replit** [comment]
I'm having this same issue. /dev/kvm exists, and qemu-kvm is installed.

```
lincoln@lincolnval:~/nixos-generators$ kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used
lincoln@lincolnval:~/nixos-generators$ ./nixos-generate -f gce
this derivation will be built:
  /nix/store/zjj2mbkc859vvlvj7dxrsr7v05p9zf6p-google-compute-image.drv
error: a 'x86_64-linux' with features {kvm} is required to build '/nix/store/zjj2mbkc859vvlvj7dxrsr7v05p9zf6p-google-compute-image.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, nixos-test, recursive-nix}
```

This is on a GCE vm with nested virtualization enabled. I also have VirtualBox installed on this machine and am able to create Ubuntu vms without issue.

Any other diagnostic info I can provide to help figure out what's going on?

**Comment by Mic92** [comment]
Does you `/etc/nix/nix.conf` in the host/container where you installed nix contain a line like?

```
system-features = nixos-test benchmark big-parallel kvm
```

**Comment by lincoln-replit** [comment]
> Does your `/etc/nix/nix.conf` in the host/container where you installed nix contain a line like?

I don't understand the question -- I haven't installed Nix, I'm running this command from a Ubuntu machine.

**Comment by Mic92** [comment]
> > Does your `/etc/nix/nix.conf` in the host/container where you installed nix contain a line like?
> 
> I don't understand the question -- I haven't installed Nix, I'm running this command from a Ubuntu machine.

Than create this file `/etc/nix/nix.conf` and add this line:

```
system-features = nixos-test benchmark big-parallel kvm
```

**Comment by ikselven** [comment]
> > > Does your `/etc/nix/nix.conf` in the host/container where you installed nix contain a line like?
> > 
> > 
> > I don't understand the question -- I haven't installed Nix, I'm running this command from a Ubuntu machine.
> 
> Than create this file `/etc/nix/nix.conf` and add this line:
> 
> ```
> system-features = nixos-test benchmark big-parallel kvm
> ```

Had the same issue with the docker image and adding this line fixed the problem. Thanks!

**Comment by lvitaly** [comment]
I was trying to run `nix-build` inside the docker container (image `nixos/nix:2.11.1`) and got the same error.
```
error: a 'x86_64-linux' with features {kvm} is required to build '/nix/store/c36j7rn8nx5mycb5awqxwsq97q3iyyh2-docker-layer-shell-ci.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, nixos-test, uid-range}
```
The container itself is running inside gitlab-runner. Do you know any tricks on how to solve this issue there?

**Comment by tartavull** [comment]
Similar issue as @lvitaly when running as a github action.

**Comment by samchan0221** [comment]
Same issue when running as github action, is self-host runinng the only way to go?

**Comment by Lassulus** [comment]
I thought I added opportunistic kvm to nixpkgs last year. Maybe it broke again. Will take a look

**Comment by ashwinmathi** [comment]
I'm also hitting this issue when trying to build in a docker container with the nixos/nix:2.12.0 image. It builds fine when I build directly on my laptop running nixos, but I get this error when trying to build in the gitlab-runner docker executor

`error: builder for '/nix/store/akihbn0zpk082adnfn3waz0qp69rvxqh-nixos-bootstrap-x86_64-linux.drv' failed with exit code 139;
       last 10 log lines:
       > qemu-kvm: falling back to tcg
       > cSeaBIOS (version rel-1.16.2-0-gea1b7a073390-prebuilt.qemu.org)
       >
       >
       > iPXE (http://ipxe.org/) 00:03.0 CA00 PCI2.10 PnP PMM+3EFD0F00+3EF30F00 CA00
       >
       >
       >
       > Booting from ROM...
       > Probing EDD (edd=off to disable)... oc./run-vm: line 5: 11318 Segmentation fault      (core dumped) /nix/store/8l602hmnwbrqxg52d8jqjmm2zq23qc3s-qemu-host-cpu-only-8.1.0/bin/qemu-kvm -cpu max -nographic -no-reboot -device virtio-rng-pci -virtfs local,path=/nix/store,security_model=none,mount_tag=store -virtfs local,path=/tmp/nix-build-nixos-bootstrap-x86_64-linux.drv-0/xchg,security_model=none,mount_tag=xchg -drive file=nixos.raw,if=virtio,cache=unsafe,werror=report -kernel /nix/store/1i65cd2vzinazszsp79gg3pnwc5y437d-linux-6.1.51/bzImage -initrd /nix/store/jnw7z005g0z5h4za5y21prhzfzk9br2m-initrd/initrd -append "console=ttyS0 panic=1 command=/nix/store/zphnw2hn2jy0kd73fd0bzj0fq94ln0hb-vm-run-stage2 out=/nix/store/mdq09hxvihbssqh6v8wacr84ilg6c375-nixos-bootstrap-x86_64-linux mountDisk= loglevel=4" -m 1024 -smp cpus=8`

**Comment by ptrsr** [comment]
Just wanted to add this here for clarity; the current way to build WITHOUT `kvm` is to add the `kvm` flag to the `system-features` list in the `nix.conf`. The build will then fall back to the non-kvm virtual machine configuration to build the image.

So in the end, you have to add the `kvm` flag to support building without `kvm`... Super confusing.
